@startuml
left to right direction
skinparam packageStyle rectangle

actor "Бухгалтер" as Accountant
actor "Руководитель" as Admin

rectangle "Система учёта доходов и расходов" {

  usecase "Вход в систему" as UC_Login_Acc
  usecase "Главное меню бухгалтера" as UC_Menu_Acc
  
  usecase "Вход в систему" as UC_Login_Admin
  usecase "Главное меню руководителя" as UC_Menu_Admin
  
  usecase "Посмотреть операции" as UC_ViewOps
  usecase "Посмотреть баланс" as UC_ViewBalance
  
  usecase "Добавить операцию" as UC_AddOp
  usecase "Изменить свои данные" as UC_EditSelf

  usecase "Регистрация нового пользователя" as UC_RegUser
  usecase "Удаление пользователя" as UC_DelUser
  usecase "Изменение данных пользователя" as UC_EditUser

  Accountant -- UC_Login_Acc
  UC_Login_Acc -- UC_Menu_Acc
  
  UC_Menu_Acc -- UC_AddOp
  UC_Menu_Acc -- UC_EditSelf
  UC_Menu_Acc -- UC_ViewOps
  UC_Menu_Acc -- UC_ViewBalance

  Admin -- UC_Login_Admin
  UC_Login_Admin -- UC_Menu_Admin
  
  UC_Menu_Admin -- UC_RegUser
  UC_Menu_Admin -- UC_DelUser
  UC_Menu_Admin -- UC_EditUser
  UC_Menu_Admin -- UC_ViewOps
  UC_Menu_Admin -- UC_ViewBalance
}
@enduml